# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

def triangle(num)
	num * (num + 1) / 2
end

def pentagonal(num)
	num * (3 * num - 1) / 2
end

def hexagonal(num)
	num * (2 * num - 1)	
end

triangles = []
pentagonals = []
hexagonals = []

(1..100000).each do |num|
	triangles << triangle(num)
end

(1..100000).each do |num|
	pentagonals << pentagonal(num)
end

(1..100000).each do |num|
	hexagonals << hexagonal(num)
end

puts (triangles & pentagonals & hexagonals).last